#!/bin/bash

#SBATCH --job-name=TRAINCIFAR10
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --gres=gpu:1
#SBATCH --time=48:00:00
#SBATCH --mem=32000M
#SBATCH --partition=gpu_titanrtx
#SBATCH --output=out/slurm_%A.out

source load.sh

srun python3 main.py --multirun main.model=supermask_convnet_3c "+models.supermask_convnet.sparsity=range(0.1,1.0,0.1)" dl.epochs=100 main.dataset=cifar10 dl.optimizer=sgd dl.lr=0.1 dl.momentum=0.9 dl.batch_size=128 dl.weight_decay=0.0001 dl.scheduler=cosine