# Grabs the default configuration for training
defaults:
  - /main@main
  - /deep_learning@dl
  - /classifier@cls
  - /swav@swav
  - /model/clip@model.clip
  - /model/repro@model.repro
  - /model/timm@model.timm
  - /model/pret@model.pret
  # https://hydra.cc/docs/1.0/plugins/joblib_launcher/
#  - override hydra/launcher: joblib
