python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=ucf101 dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.957 model.pret.kaiming_scores_init=1 main.load_checkpoint=SUB-1383/last.ckpt main.train=0 main.probe=1 &

#python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=oxfordpets dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.993 model.pret.kaiming_scores_init=1 main.load_checkpoint=SUB-1382/last.ckpt main.train=0 main.probe=1 &

python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=flowers dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.986 model.pret.kaiming_scores_init=1 main.load_checkpoint=SUB-1378/last.ckpt main.train=0 main.probe=1 ;

#python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=eurosat dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.967 model.pret.kaiming_scores_init=1 main.load_checkpoint=SUB-1376/last.ckpt main.train=0 main.probe=1;

python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=cifar100 dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.925 model.pret.kaiming_scores_init=1 main.load_checkpoint=SUB-1374/last.ckpt main.train=0 main.probe=1 ;

python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=sun397 dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.944 model.pret.kaiming_scores_init=1 main.load_checkpoint=SUB-1373/last.ckpt main.train=0 main.probe=1 &

python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=dtd dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.988 model.pret.kaiming_scores_init=1 main.load_checkpoint=SUB-1371/last.ckpt main.train=0 main.probe=1 &

#python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=cifar10 dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.914 model.pret.kaiming_scores_init=1 main.load_checkpoint=SUB-1365/last.ckpt main.train=0 main.probe=1;
