./run.sh python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=multicrop_ucf101 dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.957 model.pret.kaiming_scores_init=1 model.pret.prune_k_start=1.0 model.pret.prune_progressive=1

./run.sh python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=multicrop_flowers dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.986 model.pret.kaiming_scores_init=1  model.pret.prune_k_start=1.0 model.pret.prune_progressive=1

./run.sh python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=multicrop_eurosat dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.967 model.pret.kaiming_scores_init=1  model.pret.prune_k_start=1.0 model.pret.prune_progressive=1

./run.sh python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=multicrop_cifar100 dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.925 model.pret.kaiming_scores_init=1  model.pret.prune_k_start=1.0 model.pret.prune_progressive=1

./run.sh python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=multicrop_sun397 dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.944 model.pret.kaiming_scores_init=1  model.pret.prune_k_start=1.0 model.pret.prune_progressive=1

./run.sh python3 main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=multicrop_dtd dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.988 model.pret.kaiming_scores_init=1  model.pret.prune_k_start=1.0 model.pret.prune_progressive=1

main.py --config-name=submask_lin model.pret.source=hub model.pret.name=resnet50 model.pret.module=swav main.dataset=multicrop_cifar10 dl.scheduler=cosine cls.head_lr=0.15 cls.head_wd=0.000001 swav.queue_length=512 swav.epoch_queue_starts=30 swav.nmb_prototypes=500 dl.scheduler=cosine model.pret.prune_criterion=topk model.pret.prune_k=0.914 model.pret.kaiming_scores_init=1  model.pret.prune_k_start=1.0 model.pret.prune_progressive=1